# Generated by Django 5.2.17 on 2026-09-25 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=40)),
                ('qty_initial', models.IntegerField()),
                ('qty_available', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('quarter', models.CharField(max_length=80)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('hours_left', models.DecimalField(decimal_places=2, max_digits=6)),
                ('market_price', models.IntegerField()),
                ('published_price', models.IntegerField()),
                ('adresse_collecte', models.CharField(max_length=240)),
                ('status', models.CharField(default='live', max_length=20)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stocks',
                'managed': False,
            },
        ),
    ]
