# Generated by Django 5.2.17 on 2026-09-25 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('seller', 'Vendeur'), ('buyer', 'Acheteur')], max_length=16)),
                ('display_name', models.CharField(max_length=120)),
                ('quartier', models.CharField(blank=True, max_length=80)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('radius_km', models.FloatField(default=5)),
                ('buyer_type', models.CharField(blank=True, choices=[('restaurant', 'Restaurateur / Maquis'), ('processor', 'Transformateur'), ('household', 'Famille'), ('canteen', 'Cantine'), ('other', 'Autre')], max_length=24)),
                ('momo_alias', models.CharField(blank=True, max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
