# Generated by Django 5.2.17 on 2026-09-25 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=10)),
                ('quarter', models.CharField(max_length=80)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('radius_km', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('buyer_type', models.CharField(blank=True, max_length=40, null=True)),
                ('momo_alias', models.CharField(blank=True, max_length=80, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
    ]
