# Generated by Django 5.2.17 on 2026-09-25 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('unit_price_snapshot', models.IntegerField()),
                ('amount_due', models.IntegerField()),
                ('status', models.CharField(default='pending_payment', max_length=24)),
                ('reserved_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reservations',
                'managed': False,
            },
        ),
    ]
