# Generated by Django 5.2.17 on 2026-09-25 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('tomate', 'Tomates'), ('plantain', 'Plantains'), ('mangue', 'Mangues'), ('poisson', 'Poissons'), ('autre', 'Autre')], default='autre', max_length=24)),
                ('qty_initial', models.PositiveIntegerField()),
                ('qty_available', models.PositiveIntegerField()),
                ('unit', models.CharField(default='kg', max_length=32)),
                ('quartier', models.CharField(max_length=80)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('adresse_collecte', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('market_price', models.PositiveIntegerField(help_text='FCFA / unité')),
                ('published_price', models.PositiveIntegerField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('partial', 'Partial'), ('exhausted', 'Exhausted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='live', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField()),
                ('unit_price_snapshot', models.PositiveIntegerField()),
                ('amount_due', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending_priority', 'Pending Priority'), ('pending_payment', 'Pending Payment'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=24)),
                ('reserved_until', models.DateTimeField()),
                ('match_score', models.FloatField()),
                ('pickup_code', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='marketplace.stock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
