# Generated by Django 5.2.17 on 2026-09-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_stock_image_url_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_seller', 'Pending Seller'), ('pending_priority', 'Pending Priority'), ('pending_payment', 'Pending Payment'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=24),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
