# Generated by Django 5.2.17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_stock_freshness_analysis_buyeralert"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyeralert",
            name="kind",
            field=models.CharField(
                choices=[("match", "Nouveau lot"), ("accepted", "Commande acceptée")],
                default="match",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="buyeralert",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="marketplace.reservation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="buyeralert",
            unique_together={("buyer", "stock", "kind")},
        ),
    ]
